stages:
  - build
  - test
  - package
  - deploy

build:
  stage: build
  script:
    - echo Building
  tags:
    - runner-docker

# QA stage
checking sonarqube:
  image:
    name: sonarsource/sonar-scanner-cli:latest
  stage: test
  script:
    - export SONAR_SERVER="http://192.168.184.128:9000";
    - export GITLAB_SERVER="192.168.184.128";
    - export SONAR_TOKEN="bbc405324d527bedc8c4df24e52928dc51dd133f";
    - echo 'test code'
    - sonar-scanner -Dsonar.login=$SONAR_TOKEN 
      -Dsonar.host.url=$SONAR_SERVER
      -Dsonar.language=py
      -Dsonar.gitlab.project_id=$GITLAB_SERVER
      -Dsonar.log.level=INFO
      -Dsonar.verbose=false
      -Dsonar.python.pylint=/usr/bin/pylint -X
  tags:
    - runner-docker


package:
  stage: package
  script:
    - echo package
  tags:
    - runner-docker


deploy:
  stage: deploy
  script:
    - echo deploy
  tags:
    - runner-docker
